import type { Metadata } from "next";
import {Oleo_Script } from "next/font/google";
import "../../style/globals.css";
import Header from "@/components/header";

const roboto = Oleo_Script({
  subsets: ['latin'],
  weight: ['400', '700'], // Chỉ định trọng số
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
    className={roboto.className}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
